[package]
name = "a2"
version = "0.4.0"
authors = [
  "Julius de Bruijn <julius@nauk.io>",
  "Sergey Tkachenko <seriy.tkachenko@gmail.com>", 
]
license = "MIT"
readme  = "README.md"
description = "A native, asynchronous Apple push notification client"
keywords    = ["apns", "apple", "push", "async", "http2"]
repository  = "https://github.com/pimeys/a2.git"
homepage    = "https://github.com/pimeys/a2"
documentation = "https://pimeys.github.io/a2/"
edition = "2018"

[dependencies]
serde = "1.0"
erased-serde = "0.3"
serde_derive = "1.0"
serde_json = "1.0"
openssl = "0.10"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
http = "0.1"
base64 = "0.9"
time = "0.1"
parking_lot = "0.7"
log = "0.4"
pretty_env_logger = "0.2"
indoc = "0.2"
hyper = "0.12"
hyper-alpn = "0.1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dev-dependencies]
argparse = "0.2"
