(function() {var implementors = {};
implementors["a2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;TimeoutError&lt;<a class=\"struct\" href=\"a2/client/struct.FutureResponse.html\" title=\"struct a2::client::FutureResponse\">FutureResponse</a>&gt;&gt; for <a class=\"enum\" href=\"a2/error/enum.Error.html\" title=\"enum a2::error::Error\">Error</a>",synthetic:false,types:["a2::error::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/serde_json/1.0.20/serde_json/error/struct.Error.html\" title=\"struct serde_json::error::Error\">SerdeError</a>&gt; for <a class=\"enum\" href=\"a2/error/enum.Error.html\" title=\"enum a2::error::Error\">Error</a>",synthetic:false,types:["a2::error::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://docs.rs/openssl/0.10/openssl/error/struct.ErrorStack.html\" title=\"struct openssl::error::ErrorStack\">ErrorStack</a>&gt; for <a class=\"enum\" href=\"a2/error/enum.Error.html\" title=\"enum a2::error::Error\">Error</a>",synthetic:false,types:["a2::error::Error"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">IoError</a>&gt; for <a class=\"enum\" href=\"a2/error/enum.Error.html\" title=\"enum a2::error::Error\">Error</a>",synthetic:false,types:["a2::error::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
