(function() {var implementors = {};
implementors["a2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"a2/request/notification/struct.LocalizedAlert.html\" title=\"struct a2::request::notification::LocalizedAlert\">LocalizedAlert</a>",synthetic:false,types:["a2::request::notification::localized::LocalizedAlert"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"a2/struct.CollapseId.html\" title=\"struct a2::CollapseId\">CollapseId</a>",synthetic:false,types:["a2::request::notification::options::CollapseId"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"a2/struct.NotificationOptions.html\" title=\"struct a2::NotificationOptions\">NotificationOptions</a>",synthetic:false,types:["a2::request::notification::options::NotificationOptions"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"a2/enum.Priority.html\" title=\"enum a2::Priority\">Priority</a>",synthetic:false,types:["a2::request::notification::options::Priority"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"a2/request/payload/struct.Payload.html\" title=\"struct a2::request::payload::Payload\">Payload</a>",synthetic:false,types:["a2::request::payload::Payload"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"a2/request/payload/struct.APS.html\" title=\"struct a2::request::payload::APS\">APS</a>",synthetic:false,types:["a2::request::payload::APS"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"a2/request/payload/enum.APSAlert.html\" title=\"enum a2::request::payload::APSAlert\">APSAlert</a>",synthetic:false,types:["a2::request::payload::APSAlert"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"a2/client/enum.Endpoint.html\" title=\"enum a2::client::Endpoint\">Endpoint</a>",synthetic:false,types:["a2::client::Endpoint"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
